print("Todos los números del 0 al 10:", list(range(11)))
print("Todos los números del -10 al 0:", list(range(-10, 1, 1)))
print("Todos los números pares del 0 al 20: ", list(range(0,21,2)))
print("Todos los números impares entre el -20 y el 0: ", list(range(-19,0,2)))
print("Todos los números múltiplos de 5 del 0 al 50: ", list(range(0, 51, 5)))
